server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: WALLET-BFF
        uri: lb://WALLET-BFF
        predicates:
        - Path=/wallet/**
        filters:
        - RewritePath=/wallet/?(?<remaining>.*), /$\{remaining}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 20
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}